appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
bot: {automerge: true}
conda_forge_output_validation: true
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: voKkxqOBNM1kGAuNw3RoD7CDGOifzbHsY4A7mrcVHHdmclSqmt/xN4hkKoSag0j36rgV3ZCNOEPxvdrK/fj2dmKuM2Sep+ysoYnCOBYPof0R4h9d1W/GWA7zB57qxCbn4sv8BaFzbIR6tpcz0dMzuzw6f67JT4/OrwrCB2IIPocEWtfPlZJxedDjHCGdfVvDnucld5A6dx7OOWHgmLak4mMTiFeHBUjXw6XzzW/sLmbGQGKs4u3PX6v9QHR6mLGONXHLI8OxROdn7ZjUskmA1nEarEVq3Re7TZQFYvME0CA0SXT+39J0m7dSTsruUe9NvFirP1TdYVJLoRYaM9Z+5SR3IJRxx38aZpXNJV60CNN8Kb0GFw8jHw4HzIiRsDr2+r+tw8CSabIxQghiFVGB6tFuKP56F9D1cP3CGQqaIWI5l83ny5mENyEqYi5qfh3j/yA+xK1GbZY33fBgMpCdUnMh9Vmt42/efDFH5DuzVOMqcLmUlAk/7/Ai846rKg/0MV9qru5xenHrFZMQo9fhIT0ew8fIaVcYPGkUOTfn6skxhd2mn4cTg377PQsMRs3dLDQ67kaq4RcD7nYoVmWUXf5iD3ZXCyRU3PLFGxTYs2aMKfIxCLMohiL3jJxWiOBsyqpAmH91m+1U+fxvwNLkssYw/tZYmhvBQoxAnoCsuFM=}
